# Generated by Django 3.2 on 2021-07-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20210714_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='message.thread'),
        ),
    ]
