# Generated by Django 3.2 on 2021-07-13 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_usermessage_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
