# Generated by Django 3.2 on 2021-05-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='personal_skills', to='users.SkillTag'),
        ),
    ]
