# Generated by Django 3.2 on 2021-06-09 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210517_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
