# Generated by Django 3.2 on 2021-04-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210427_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevote',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
