# Generated by Django 3.2 on 2021-04-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articlevote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevote',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
