# Generated by Django 3.2 on 2021-04-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='tags',
        ),
    ]
