# Generated by Django 3.2 on 2021-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210517_1436'),
        ('discussion', '0002_alter_discussion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='discussion_tags', to='users.TopicTag'),
        ),
    ]
