# Generated by Django 3.2 on 2021-05-19 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumble',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
