# Generated by Django 3.2 on 2021-04-27 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210422_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumble',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.mumble'),
        ),
        migrations.AlterField(
            model_name='mumble',
            name='remumble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remumbles', to='feed.mumble'),
        ),
    ]
