# Generated by Django 3.1.7 on 2021-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
