# Generated by Django 3.1.3 on 2021-04-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='reply_at',
        ),
    ]
