# Generated by Django 3.1.3 on 2021-04-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_post_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
