# Generated by Django 3.1.3 on 2021-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
