# Generated by Django 3.2 on 2021-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210414_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remumble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original', to='base.post'),
        ),
    ]
