# Generated by Django 3.2 on 2021-04-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_post_remumble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remumble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remumbles', to='base.post'),
        ),
    ]
