# Generated by Django 3.2 on 2021-04-21 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_postvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='post_user', through='base.PostVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='value',
            field=models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=20),
        ),
    ]
